

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client/node_modules:/client/node_modules
      - ./client/public:/client/public
      - ./client/src:/client/src
      - ./client/.env:/client/.env
    env_file:
      - ./client/.env
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./server/node_modules:/server/node_modules
      - ./server/src:/server/src
      - ./server/.env:/server/.env
    env_file:
      - ./server/.env
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./server/.env

volumes:
  pgdata:
    driver: local
